apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Jenkins-Demo
  description: Jenkins Integration With Bcakstage
  links:
    - url: http://34.125.87.26:8080/
      title: Jenkins-XenonStack_Dashboard
      icon: dashboard
  annotations:
    jenkins.io/job-full-name: Backstage/backstage-demo
spec:
  type: website
  lifecycle: production
  owner: spandan


