apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: testing
  tags:
    - go
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=backstage'
    'backstage.io/kubernetes-label-selector': 'app=nginx'
spec:
  kubernetes:
    selector:
      matchLabels:
        name: dice-roller
        version: canary
  type: service
  lifecycle: production
  owner: guest
