apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Niharika_Zirvi
spec:
  profile:
    displayName: Niharika Zirvi
    email: niharika@xenonstack.com
    #picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [CloudOps, SubCoach]
