apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: XenonStack-Demo
  description: |
    A service for testing Backstage functionality. Configured for
    GitHub Actions.
  annotations:
    backstage.io/kubernetes-id: value
spec:
  type: service
  owner: Spandan Saha
  lifecycle: production
